billeterie_ticketadde1:
    path:   /Creation/Etape1/{demiJour}
    defaults: { _controller: JMBilleterieBundle:Ticket:addTicketE1 }

billeterie_ticketadde2:
    path:   /Creation/Etape2/{demiJour}/{nbBillet}
    defaults: { _controller: JMBilleterieBundle:Ticket:addTicketE2 }
    
billeterie:
    path:   /
    defaults: { _controller: JMBilleterieBundle:Ticket:view }
    
billeterie_panier:
    path:   /Panier
    defaults: { _controller: JMBilleterieBundle:Ticket:panier }
    
billeterie_panier_vider:
    path:   /Panier/clear{id}
    defaults: { _controller: JMBilleterieBundle:Ticket:panierclear }
    
billeterie_infos:
    path:   /infos
    defaults: { _controller: JMBilleterieBundle:Ticket:infos }
    
billeterie_pay_stripe:
    path:   /payement/stripe
    defaults: { _controller: JMBilleterieBundle:Payement:stripe }
    
billeterie_pay_paypal:
    path:   /payement/paypal/pay
    defaults: { _controller: JMBilleterieBundle:Payement:paypal }

billeterie_pay_paypal_success:
    path:   /payement/paypal/success
    defaults: { _controller: JMBilleterieBundle:Payement:paypalSuccess }

billeterie_pay_paypal_cancel:
    path:   /payement/paypal/cancel
    defaults: { _controller: JMBilleterieBundle:Payement:paypalReturn }

billeterie_pdf:
    path:   /pdf
    defaults: { _controller: JMBilleterieBundle:Pdf:pdf }

billeterie_after_payement:
    path:   /payement/done
    defaults: { _controller: JMBilleterieBundle:Payement:done }