billeterie_ticketadd:
    path:   /{demiJour}
    defaults: { _controller: JMBilleterieBundle:Ticket:addTicket }
    
billeterie:
    path:   /
    defaults: { _controller: JMBilleterieBundle:Ticket:view }