billeterie_ticketadd:
    path:   /creationTicket
    defaults: { _controller: JMBilleterieBundle:Ticket:addTicket }
    
billeterie:
    path:   /
    defaults: { _controller: JMBilleterieBundle:Ticket:view }