jm_contact:
    resource: "@JMContactBundle/Resources/config/routing.yml"
    prefix:   /contact

jm_billeterie:
    resource: "@JMBilleterieBundle/Resources/config/routing.yml"
    prefix:   /billeterie

core:
    path:   /
    defaults: { _controller: CoreBundle:Home:view }