<?php

namespace JM\BilleterieBundle\Repository;

/**
 * billetDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class billetDateRepository extends \Doctrine\ORM\EntityRepository
{
}
