<?php

namespace JM\BilleterieBundle\Repository;

/**
 * JourInterditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourInterditRepository extends \Doctrine\ORM\EntityRepository
{
}
