<?php

namespace JM\BilleterieBundle\Repository;

/**
 * nbBilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NbBilletRepository extends \Doctrine\ORM\EntityRepository
{
}